name: "Test CPAN distribution"
description: "Build and upload a CPAN-style archive with Dist::Zilla"
author: "Ricardo Signes"

inputs:
  dist-name:
    description: 'The name of the dist, like Your-Cool-Dist'
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"

  steps:
  - name: Setup environment variables
    shell: bash
    # some plugins still needs this to run their tests...
    run: |
      echo "PERL_USE_UNSAFE_INC=0" >> $GITHUB_ENV
      echo "AUTHOR_TESTING=1" >> $GITHUB_ENV
      echo "AUTOMATED_TESTING=1" >> $GITHUB_ENV
  - name: Download tarball
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.dist-name }}.tar.gz
  - name: Extract tarball
    shell: bash
    run: tar zxvf ${{ inputs.dist-name }}.tar.gz
  - name: Install dependencies
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: cpm install -g
  - name: Optional packed-in test step
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: |
      if [ -x ./ci/before-build ]; then
        ./ci/before-build
      else
        echo "No ./ci/before-build or it isn't +x"
      fi
  - name: Build distribution
    # This step is a bit bananas, but was suggested by WOLFSAGE, and makes
    # sense.  We want to build the distribution (like "perl Makefile.PL &&
    # make") but to do so correctly with either Makefile.PL or Build.PL.  cpanm
    # abstracts this for us.  --test-only says "do not install, just test", and
    # -n says "but run no tests".  We'll replace this with something less
    # bananas another day.
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: cpanm --test-only -n -v .
  - name: Install yath
    shell: bash
    run: cpm install -g Test2::Harness Test2::Harness::Renderer::JUnit
  - name: Run the tests
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: |
      JUNIT_TEST_FILE="/tmp/test-output.xml" ALLOW_PASSING_TODOS=1 TEST2_UUID_NO_WARN=1 yath test --renderer=Formatter --renderer=JUnit -b
  - name: Publish test report
    uses: mikepenz/action-junit-report@v4
    if: always() # always run even if the previous step fails
    with:
      check_name: JUnit Report (${{ matrix.perl-version }})
      report_paths: /tmp/test-output.xml
