name: "Test CPAN distribution"
description: "Build and upload a CPAN-style archive with Dist::Zilla"
author: "Ricardo Signes"

inputs:
  dist-name:
    description: 'The name of the dist, like Your-Cool-Dist'
    default: ${{ github.event.repository.name }}

runs:
  using: "composite"

  steps:
  - name: Setup environment variables
    shell: bash
    # some plugins still needs this to run their tests...
    run: |
      echo "PERL_USE_UNSAFE_INC=0" >> $GITHUB_ENV
      echo "AUTHOR_TESTING=1" >> $GITHUB_ENV
      echo "AUTOMATED_TESTING=1" >> $GITHUB_ENV
  - name: Download tarball
    uses: actions/download-artifact@v4
    with:
      name: ${{ inputs.dist-name }}.tar.gz
  - name: Extract tarball
    shell: bash
    run: tar zxvf ${{ inputs.dist-name }}.tar.gz
  - name: Install dependencies
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: cpm install -g
  - name: Makefile.PL
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: perl Makefile.PL
  - name: Install yath
    shell: bash
    run: cpm install -g Test2::Harness Test2::Harness::Renderer::JUnit
  - name: Run the tests
    working-directory: ./${{ inputs.dist-name }}
    shell: bash
    run: |
      JUNIT_TEST_FILE="/tmp/test-output.xml" ALLOW_PASSING_TODOS=1 yath test --renderer=Formatter --renderer=JUnit -D
  - name: Publish test report
    uses: mikepenz/action-junit-report@v4
    if: always() # always run even if the previous step fails
    with:
      check_name: JUnit Report (${{ matrix.perl-version }})
      report_paths: /tmp/test-output.xml
