name: "multiperl test"
on:
  workflow_call:
    inputs:
      install-dzil-from-cpan:
        description: 'If true, get a Dist::Zilla install from CPAN, not apt'
        type: string
        default: false

jobs:
  build-tarball:
    name: "Build dist archive"
    runs-on: ubuntu-latest
    outputs:
      perl-versions: ${{ steps.build-archive.outputs.perl-versions }}
    steps:
    - name: Build archive
      id: build-archive
      uses: rjbs/dzil-actions/build@v0
      with:
        install-dzil-from-cpan: ${{ inputs.install-dzil-from-cpan }}

  multiperl-test:
    name: "Run dist tests"
    needs: build-tarball
    uses: rjbs/dzil-actions/.github/workflows/multiperl-test-matrix.yaml@v0
    with:
      perl-versions-json: ${{ needs.build-tarball.outputs.perl-versions }}

